# Generated by Django 5.1.3 on 2026-03-18 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import referrals.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0013_rename_payments_ea_public__idx_payments_ea_public__06ea53_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('referrer_reward_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('referred_reward_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reward_type', models.CharField(choices=[('credits', 'Credits'), ('cash', 'Cash'), ('discount', 'Discount')], default='credits', max_length=20)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('conversion_criteria', models.CharField(choices=[('signup', 'Signup'), ('first_purchase', 'First Purchase'), ('min_purchase', 'Minimum Purchase')], default='first_purchase', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_referrals_per_user', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'start_date'], name='referrals_r_is_acti_c3c64c_idx'), models.Index(fields=['reward_type'], name='referrals_r_reward__5c4784_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('campaign_code', models.CharField(max_length=20, unique=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='referrals.referralprogram')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign_code'], name='referrals_r_campaig_d6061c_idx'), models.Index(fields=['program', 'is_active'], name='referrals_r_program_7a20ab_idx'), models.Index(fields=['start_date', 'end_date'], name='referrals_r_start_d_176dbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=referrals.models.generate_referral_code, max_length=20, unique=True)),
                ('email_sent_to', models.EmailField(blank=True, max_length=254)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('referrer_reward_status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('referred_reward_status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('referrer_reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('referred_reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('qualifying_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_referrals', to='payments.order')),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralprogram')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='referrals_r_code_559b5e_idx'), models.Index(fields=['referrer', 'status'], name='referrals_r_referre_ebbb80_idx'), models.Index(fields=['referred'], name='referrals_r_referre_f289d6_idx'), models.Index(fields=['status', 'created_at'], name='referrals_r_status_2b2ceb_idx'), models.Index(fields=['program', 'status'], name='referrals_r_program_a0ce84_idx')],
            },
        ),
    ]
