# Generated by Django 5.1.7 on 2025-03-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time_expected", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_canceled", models.BooleanField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_rescheduled", models.BooleanField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "credit_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("practitioner_note", models.TextField(blank=True, null=True)),
                (
                    "canceled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Client"),
                            ("practitioner", "Practitioner"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("canceled_date", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("is_group", models.BooleanField(blank=True, null=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("attendance_duration", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "bookings",
                "db_table_comment": "Booking for session and bundle",
            },
        ),
        migrations.CreateModel(
            name="BookingReminders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "booking_reminders",
            },
        ),
    ]
