# Generated by Django 5.1.3 on 2025-06-10 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public UUID for API exposure', unique=True)),
                ('start_time', models.DateTimeField(help_text='Scheduled start time')),
                ('end_time', models.DateTimeField(help_text='Scheduled end time')),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for this booking', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Custom booking title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Booking description or notes', null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes from the client', null=True)),
                ('practitioner_notes', models.TextField(blank=True, help_text='Private notes from practitioner', null=True)),
                ('meeting_url', models.URLField(blank=True, help_text='Virtual meeting link', null=True)),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting ID or room number', max_length=100, null=True)),
                ('price_charged_cents', models.IntegerField(help_text='Amount charged for this booking in cents')),
                ('discount_amount_cents', models.IntegerField(default=0, help_text='Discount applied in cents')),
                ('final_amount_cents', models.IntegerField(help_text='Final amount after discounts in cents')),
                ('service_name_snapshot', models.CharField(blank=True, help_text='Service name at time of booking', max_length=255)),
                ('service_description_snapshot', models.TextField(blank=True, help_text='Service description at time of booking')),
                ('practitioner_name_snapshot', models.CharField(blank=True, help_text='Practitioner name at time of booking', max_length=255)),
                ('service_duration_snapshot', models.PositiveIntegerField(blank=True, help_text='Duration in minutes at time of booking', null=True)),
                ('package_name_snapshot', models.CharField(blank=True, help_text='Package name at time of booking', max_length=255)),
                ('package_contents_snapshot', models.JSONField(blank=True, help_text='What was included in package at time of booking', null=True)),
                ('bundle_name_snapshot', models.CharField(blank=True, help_text='Bundle name at time of booking', max_length=255)),
                ('bundle_sessions_snapshot', models.PositiveIntegerField(blank=True, help_text='Total sessions in bundle at time of booking', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('practitioner', 'Practitioner'), ('system', 'System'), ('admin', 'Admin')], max_length=20, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True, help_text='When status last changed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When booking was confirmed', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When service started', null=True)),
                ('is_package_purchase', models.BooleanField(default=False, help_text='Whether this is a package purchase')),
                ('is_bundle_purchase', models.BooleanField(default=False, help_text='Whether this is a bundle purchase')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Max participants for this booking')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Whether note is visible only to practitioners')),
            ],
            options={
                'verbose_name': 'Booking Note',
                'verbose_name_plural': 'Booking Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='When to send the reminder')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When reminder was actually sent', null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking Reminder',
                'verbose_name_plural': 'Booking Reminders',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
