# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location if in-person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='utils.address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='Parent booking for packages/bundles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_bookings', to='bookings.booking'),
        ),
    ]
