# Generated by Django 5.1.8 on 2025-05-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_user_id_69a5d5_idx',
            old_name='bookings_user_id_1eeb34_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_practit_b87758_idx',
            old_name='bookings_practit_17fcf9_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_service_e27d43_idx',
            old_name='bookings_service_7029d7_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingreminders',
            new_name='bookings_bo_booking_5e149c_idx',
            old_name='booking_rem_booking_ff652f_idx',
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bookingreminders',
            table=None,
        ),
    ]
