# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_session',
            field=models.ForeignKey(blank=True, help_text='Specific session for workshops/courses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicesession'),
        ),
    ]
