# Generated by Django 5.1.3 on 2025-06-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_initial'),
        ('services', '0003_package_packageservice_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Bundle this booking is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.bundle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_bundle_purchase',
            field=models.BooleanField(default=False, help_text='Whether this is a bundle purchase'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_package_purchase',
            field=models.BooleanField(default=False, help_text='Whether this is a package purchase'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package this booking is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.package'),
        ),
    ]
