# Generated by Django 5.1.3 on 2025-11-14 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_metadata'),
        ('payments', '0008_make_tier_code_required'),
        ('practitioners', '0008_add_current_subscription'),
        ('rooms', '0004_merge_20250706_0656'),
        ('services', '0013_make_service_slug_required'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_valid_time_range',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled end time', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time', null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR'), name='booking_valid_time_range'),
        ),
    ]
