# Generated by Django 5.1.3 on 2025-11-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_make_booking_times_nullable'),
        ('payments', '0009_add_projected_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_transaction',
        ),
        migrations.AddField(
            model_name='booking',
            name='credit_usage_transaction',
            field=models.ForeignKey(blank=True, help_text='Specific credit usage transaction (if credits applied)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.usercredittransaction'),
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Financial transaction for this booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use order relationship instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_bookings', to='bookings.booking'),
        ),
    ]
