# Generated by Django 5.1.3 on 2025-11-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_unused_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE bookings_booking DROP COLUMN IF EXISTS meeting_url;',
            reverse_sql='ALTER TABLE bookings_booking ADD COLUMN meeting_url VARCHAR(500);'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE bookings_booking DROP COLUMN IF EXISTS meeting_id;',
            reverse_sql='ALTER TABLE bookings_booking ADD COLUMN meeting_id VARCHAR(100);'
        ),
    ]
