# Generated by Django 5.1.3 on 2025-11-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_make_service_session_required'),
        ('services', '0020_rename_service_ses_service_idx_service_ses_service_c06988_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Track on ServiceSession', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Track on ServiceSession', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use service_session.end_time', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_session',
            field=models.ForeignKey(blank=True, help_text='The scheduled session this booking reserves a seat in (will become required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicesession'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use service_session.start_time', null=True),
        ),
    ]
