# Generated by Django 5.1.3 on 2025-11-21 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_remove_package_bundle_flags'),
        ('payments', '0010_add_package_metadata'),
        ('practitioners', '0010_add_feature_request_model'),
        ('services', '0023_add_actual_times_remove_room_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_valid_time_range',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_practit_b87758_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_3c2736_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_parent__2d389a_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_start_t_1c7039_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parent_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['practitioner', 'status'], name='bookings_bo_practit_1f2a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['order'], name='bookings_bo_order_i_09a4cb_idx'),
        ),
    ]
