# Generated by Django 5.1.3 on 2025-11-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_deprecated_booking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='practitioner_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_description_snapshot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_duration_snapshot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_name_snapshot',
        ),
    ]
