# Generated by Django 5.1.3 on 2025-11-21 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_remove_booking_snapshot_fields'),
        ('payments', '0010_add_package_metadata'),
        ('practitioners', '0010_add_feature_request_model'),
        ('services', '0023_add_actual_times_remove_room_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_non_negative_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount_cents',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_amount_cents',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price_charged_cents',
        ),
        migrations.AddField(
            model_name='booking',
            name='credits_allocated',
            field=models.IntegerField(default=0, help_text='Credit value allocated to this booking in cents'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('credits_allocated__gte', 0)), name='booking_non_negative_credits'),
        ),
    ]
