# Generated by Django 5.1.3 on 2025-11-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_remove_pricing_add_credits_allocated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='credit_usage_transaction',
        ),
    ]
