# Generated by Django 5.1.3 on 2026-03-24 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_add_completed_booking_status'),
        ('payments', '0013_rename_payments_ea_public__idx_payments_ea_public__06ea53_idx_and_more'),
        ('practitioners', '0011_add_answer_to_question'),
        ('services', '0027_add_session_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Financial transaction for this booking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='payments.order'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending_payment'])), fields=('user', 'service_session'), name='unique_active_booking_per_user_session'),
        ),
    ]
