# Generated by Django 5.1.3 on 2026-03-24 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_production_readiness_fixes'),
        ('payments', '0013_rename_payments_ea_public__idx_payments_ea_public__06ea53_idx_and_more'),
        ('practitioners', '0011_add_answer_to_question'),
        ('services', '0027_add_session_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_session', 'status'], name='bookings_bo_service_56fe6f_idx'),
        ),
    ]
