# Generated by Django 5.1.3 on 2025-07-05 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_key',
            field=models.CharField(blank=True, help_text="Unique key to prevent duplicate notifications (e.g. 'booking_123_24h_reminder')", max_length=100),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_key'], name='notificatio_notific_a6d7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_key', 'status'], name='notificatio_user_id_2ba844_idx'),
        ),
    ]
