import type { StreamPost, FeaturedPractitioner } from "@/types/stream"

// Mock data for stream posts
export function getMockStreamPosts(): StreamPost[] {
  return [
    {
      id: "post1",
      practitionerId: "pract1",
      practitionerName: "Dr. Sarah Johnson",
      practitionerImage: "/images/avatar-2.png",
      content:
        "Today I'm sharing my morning meditation routine that helps set a positive tone for the day. This simple 10-minute practice can transform your mindset and energy levels.",
      mediaUrls: ["/mindful-breath.png"],
      contentType: "image",
      isPremium: false,
      createdAt: "2023-04-15T08:30:00Z",
      likes: 124,
      comments: 18,
      views: 1240,
      tags: ["Meditation", "Mindfulness", "Morning Routine"],
      commentsList: [
        {
          id: "comment1",
          postId: "post1",
          userId: "user1",
          userName: "Michael P.",
          userImage: "/abstract-user-icon.png",
          content: "This has been life-changing for me. Thank you for sharing!",
          createdAt: "2023-04-15T10:15:00Z",
          likes: 5,
        },
        {
          id: "comment2",
          postId: "post1",
          userId: "user2",
          userName: "Jessica T.",
          userImage: "/abstract-user-icon.png",
          content: "How long did it take you to establish this as a consistent habit?",
          createdAt: "2023-04-15T11:30:00Z",
          likes: 2,
        },
      ],
    },
    {
      id: "post2",
      practitionerId: "pract2",
      practitionerName: "Alex Rivera",
      practitionerImage: "/practitioner-1.jpg",
      content:
        "I'm excited to share this exclusive breathwork technique that I've developed over the past decade. This advanced practice helps release deep-seated tension and emotional blockages.",
      mediaUrls: ["/serene-forest-meditation.png"],
      contentType: "video",
      isPremium: true,
      createdAt: "2023-04-14T15:45:00Z",
      likes: 89,
      comments: 7,
      views: 560,
      tags: ["Breathwork", "Emotional Healing", "Advanced Practice"],
      commentsList: [
        {
          id: "comment3",
          postId: "post2",
          userId: "user3",
          userName: "Samantha K.",
          userImage: "/abstract-user-icon.png",
          content: "Worth every penny of my subscription. This technique is incredible!",
          createdAt: "2023-04-14T16:20:00Z",
          likes: 8,
        },
      ],
    },
    {
      id: "post3",
      practitionerId: "pract3",
      practitionerName: "Marcus Chen",
      practitionerImage: "/practitioner-2.jpg",
      content:
        "The connection between nutrition and mental clarity is often overlooked. Here are my top 5 foods that support cognitive function and emotional balance.",
      mediaUrls: [],
      contentType: "article",
      isPremium: false,
      createdAt: "2023-04-13T11:20:00Z",
      likes: 215,
      comments: 32,
      views: 1890,
      tags: ["Nutrition", "Mental Health", "Wellness"],
      commentsList: [
        {
          id: "comment4",
          postId: "post3",
          userId: "user4",
          userName: "David L.",
          userImage: "/abstract-user-icon.png",
          content: "I've been incorporating these foods and noticed a huge difference in my focus!",
          createdAt: "2023-04-13T12:45:00Z",
          likes: 12,
        },
        {
          id: "comment5",
          postId: "post3",
          userId: "user5",
          userName: "Rachel W.",
          userImage: "/abstract-user-icon.png",
          content: "Any suggestions for those with dietary restrictions?",
          createdAt: "2023-04-13T14:10:00Z",
          likes: 3,
        },
      ],
    },
    {
      id: "post4",
      practitionerId: "pract4",
      practitionerName: "Emma Wilson",
      practitionerImage: "/practitioner-3.jpg",
      content:
        "Join me for this guided visualization to connect with your inner wisdom. This practice has helped my clients make important life decisions with greater clarity and confidence.",
      mediaUrls: ["/secluded-mountain-cabin.png"],
      contentType: "audio",
      isPremium: true,
      createdAt: "2023-04-12T09:15:00Z",
      likes: 76,
      comments: 9,
      views: 420,
      tags: ["Guided Meditation", "Visualization", "Inner Wisdom"],
      commentsList: [],
    },
    {
      id: "post5",
      practitionerId: "pract1",
      practitionerName: "Dr. Sarah Johnson",
      practitionerImage: "/images/avatar-2.png",
      content:
        "The science behind mindfulness is fascinating. Here's a breakdown of how regular meditation actually changes your brain structure and function over time.",
      mediaUrls: [],
      contentType: "article",
      isPremium: false,
      createdAt: "2023-04-11T14:30:00Z",
      likes: 198,
      comments: 24,
      views: 1560,
      tags: ["Neuroscience", "Mindfulness", "Research"],
      commentsList: [],
    },
    {
      id: "post6",
      practitionerId: "pract5",
      practitionerName: "Jordan Taylor",
      practitionerImage: "/practitioner-4.jpg",
      content:
        "This 15-minute yoga sequence is perfect for releasing tension after a long day of sitting. Accessible for all levels and requires no special equipment.",
      mediaUrls: ["/mindful-yoga-community.png"],
      contentType: "video",
      isPremium: false,
      createdAt: "2023-04-10T17:45:00Z",
      likes: 312,
      comments: 41,
      views: 2780,
      tags: ["Yoga", "Stress Relief", "Movement"],
      commentsList: [],
    },
    {
      id: "post7",
      practitionerId: "pract2",
      practitionerName: "Alex Rivera",
      practitionerImage: "/practitioner-1.jpg",
      content:
        "Exclusive for my subscribers: My complete guide to establishing a home meditation practice, including space setup, timing considerations, and troubleshooting common challenges.",
      mediaUrls: ["/serene-massage.png"],
      contentType: "image",
      isPremium: true,
      createdAt: "2023-04-09T10:20:00Z",
      likes: 64,
      comments: 5,
      views: 380,
      tags: ["Meditation", "Home Practice", "Beginners"],
      commentsList: [],
    },
    {
      id: "post8",
      practitionerId: "pract3",
      practitionerName: "Marcus Chen",
      practitionerImage: "/practitioner-2.jpg",
      content:
        "The relationship between gut health and mood is stronger than most people realize. Here's what you need to know about your microbiome and emotional wellbeing.",
      mediaUrls: [],
      contentType: "article",
      isPremium: false,
      createdAt: "2023-04-08T13:10:00Z",
      likes: 178,
      comments: 22,
      views: 1420,
      tags: ["Gut Health", "Nutrition", "Mental Health"],
      commentsList: [],
    },
    {
      id: "post9",
      practitionerId: "pract4",
      practitionerName: "Emma Wilson",
      practitionerImage: "/practitioner-3.jpg",
      content:
        "Premium content: Deep dive into shadow work - how to safely explore and integrate the parts of yourself that you typically hide or repress. Includes guided journal prompts.",
      mediaUrls: ["/guiding-light-path.png"],
      contentType: "image",
      isPremium: true,
      createdAt: "2023-04-07T16:30:00Z",
      likes: 92,
      comments: 11,
      views: 510,
      tags: ["Shadow Work", "Self-Discovery", "Journal Prompts"],
      commentsList: [],
    },
    {
      id: "post10",
      practitionerId: "pract5",
      practitionerName: "Jordan Taylor",
      practitionerImage: "/practitioner-4.jpg",
      content:
        "How to maintain your wellness practice while traveling. These simple techniques can be done anywhere, even in a hotel room or on a plane.",
      mediaUrls: ["/diverse-group-city.png"],
      contentType: "video",
      isPremium: false,
      createdAt: "2023-04-06T08:45:00Z",
      likes: 245,
      comments: 29,
      views: 1980,
      tags: ["Travel", "Wellness", "Adaptability"],
      commentsList: [],
    },
  ]
}

// Mock data for featured practitioners
export function getMockFeaturedPractitioners(): FeaturedPractitioner[] {
  return [
    {
      id: "pract1",
      name: "Dr. Sarah Johnson",
      image: "/images/avatar-2.png",
      coverImage: "/mindful-breath.png",
      title: "Mindfulness Coach & Neuroscientist",
      tags: ["Meditation", "Neuroscience", "Stress Management"],
      subscriberCount: 1240,
      postCount: 87,
    },
    {
      id: "pract2",
      name: "Alex Rivera",
      image: "/practitioner-1.jpg",
      coverImage: "/serene-forest-meditation.png",
      title: "Breathwork Specialist",
      tags: ["Breathwork", "Trauma Release", "Emotional Healing"],
      subscriberCount: 890,
      postCount: 62,
    },
    {
      id: "pract3",
      name: "Marcus Chen",
      image: "/practitioner-2.jpg",
      coverImage: "/diverse-medical-team.png",
      title: "Holistic Nutritionist",
      tags: ["Nutrition", "Gut Health", "Functional Medicine"],
      subscriberCount: 1560,
      postCount: 104,
    },
    {
      id: "pract4",
      name: "Emma Wilson",
      image: "/practitioner-3.jpg",
      coverImage: "/guiding-light-path.png",
      title: "Intuitive Guide & Meditation Teacher",
      tags: ["Guided Meditation", "Shadow Work", "Inner Wisdom"],
      subscriberCount: 720,
      postCount: 53,
    },
    {
      id: "pract5",
      name: "Jordan Taylor",
      image: "/practitioner-4.jpg",
      coverImage: "/mindful-yoga-community.png",
      title: "Yoga Instructor & Movement Specialist",
      tags: ["Yoga", "Movement", "Flexibility"],
      subscriberCount: 1870,
      postCount: 129,
    },
  ]
}
