version: '3.1'

volumes:
  postgres-data:

services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  admin:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn estuary.asgi:application --host 0.0.0.0 --reload
    depends_on:
      - postgres

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - '8001:8000'
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn api.main:app --host 0.0.0.0 --reload
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
    image: frontend:latest
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: yarn dev
    depends_on:
      - api

  frontend-2:
    build:
      context: frontend-2
      dockerfile: Dockerfile.dev
    image: frontend-2:dev
    ports:
      - '3001:3001'
    volumes:
      - ./frontend-2:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://admin:8000
      - NEXT_PUBLIC_WS_URL=ws://admin:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3001
      - NEXTAUTH_URL_INTERNAL=http://admin:8000
      - PORT=3001
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51RYVT4I79x8ltrHuOxx5PkP7sQf42FQAtUPmJyaREnFwPwgU8WPdQxqM2P6Ll8q5cI5uYBc0EpW9OpVApVcubE5Z004JjhTdrq
    depends_on:
      - admin

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - admin
      - api
