# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("daily_room_name", models.TextField()),
                ("daily_room_url", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomBookingRelation",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bookings.booking",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rooms.room"
                    ),
                ),
            ],
            options={
                "db_table": "room_booking_relations",
            },
        ),
        migrations.CreateModel(
            name="VideoToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField()),
                ("role", models.TextField()),
                ("permissions", models.JSONField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(blank=True, null=True)),
                ("is_revoked", models.BooleanField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bookings.booking",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rooms.room"
                    ),
                ),
            ],
            options={
                "db_table": "video_tokens",
            },
        ),
    ]
