# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_room_name', models.CharField(max_length=255, unique=True)),
                ('daily_room_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('error', 'Error')], default='active', max_length=20)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['daily_room_name'], name='rooms_room_daily_r_822074_idx'), models.Index(fields=['status', 'created_at'], name='rooms_room_status_576d1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomBookingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_relations', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_relations', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='VideoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('participant', 'Participant'), ('observer', 'Observer')], default='participant', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_tokens', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='rooms.room')),
            ],
        ),
    ]
