# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videotoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roombookingrelation',
            index=models.Index(fields=['room'], name='rooms_roomb_room_id_ac5e77_idx'),
        ),
        migrations.AddIndex(
            model_name='roombookingrelation',
            index=models.Index(fields=['booking'], name='rooms_roomb_booking_daf2ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roombookingrelation',
            unique_together={('room', 'booking')},
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['user', 'room'], name='rooms_video_user_id_d3f38c_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['token'], name='rooms_video_token_d0976c_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['expires_at'], name='rooms_video_expires_f92ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['is_used', 'is_revoked'], name='rooms_video_is_used_c07af6_idx'),
        ),
    ]
