# Generated by Django 5.1.8 on 2025-05-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roombookingrelation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='videotoken',
            table=None,
        ),
    ]
