# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_initial'),
        ('rooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomrecording',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtemplate'),
        ),
        migrations.AddField(
            model_name='roomtoken',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='rooms.roomparticipant'),
        ),
        migrations.AddField(
            model_name='roomtoken',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roomtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videotoken',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_tokens', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='videotoken',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_tokens', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='videotoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roombookingrelation',
            index=models.Index(fields=['room'], name='rooms_roomb_room_id_ac5e77_idx'),
        ),
        migrations.AddIndex(
            model_name='roombookingrelation',
            index=models.Index(fields=['booking'], name='rooms_roomb_booking_daf2ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roombookingrelation',
            unique_together={('room', 'booking')},
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['room', 'user'], name='rooms_roomp_room_id_c911db_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['participant_sid'], name='rooms_roomp_partici_b7c8bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'identity')},
        ),
        migrations.AddIndex(
            model_name='roomrecording',
            index=models.Index(fields=['recording_id'], name='rooms_roomr_recordi_ac41e7_idx'),
        ),
        migrations.AddIndex(
            model_name='roomrecording',
            index=models.Index(fields=['room', 'status'], name='rooms_roomr_room_id_5518e2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['livekit_room_name'], name='rooms_room_livekit_63994b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'created_at'], name='rooms_room_status_576d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['booking'], name='rooms_room_booking_8456c7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['service_session'], name='rooms_room_service_86ecca_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['scheduled_start'], name='rooms_room_schedul_f1ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtoken',
            index=models.Index(fields=['token'], name='rooms_roomt_token_4207d2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtoken',
            index=models.Index(fields=['user', 'room'], name='rooms_roomt_user_id_45aff6_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtoken',
            index=models.Index(fields=['expires_at'], name='rooms_roomt_expires_b4d0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtoken',
            index=models.Index(fields=['is_used', 'is_revoked'], name='rooms_roomt_is_used_7bfe23_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['user', 'room'], name='rooms_video_user_id_d3f38c_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['token'], name='rooms_video_token_d0976c_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['expires_at'], name='rooms_video_expires_f92ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='videotoken',
            index=models.Index(fields=['is_used', 'is_revoked'], name='rooms_video_is_used_c07af6_idx'),
        ),
    ]
