# Generated by Django 5.1.3 on 2025-07-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_initial'),
        ('rooms', '0003_room_created_by_alter_room_name'),
    ]

    operations = [
    ]
