# Generated by Django 5.1.3 on 2025-11-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_booking_fk'),
        ('services', '0026_populate_service_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_room_booking_8456c7_idx',
        ),
        migrations.AddField(
            model_name='roomrecording',
            name='is_available',
            field=models.BooleanField(default=True, help_text='If False, recording is hidden from clients'),
        ),
        migrations.AlterField(
            model_name='room',
            name='service_session',
            field=models.OneToOneField(blank=True, help_text='The session this room is for. Access bookings via service_session.bookings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livekit_room', to='services.servicesession'),
        ),
    ]
