"""
Courier Template Configuration
This file contains all Courier template IDs used throughout the application.
These are static configuration values that don't change between environments.
"""

# Client Email Templates
CLIENT_TEMPLATES = {
    'WELCOME': 'DS2P0KTZPM4K5MM018DJSWEMX8Q1',
    'EMAIL_VERIFICATION': 'BT1EYXR62RMP0VK26PHXW4B1PQH6',
    'BOOKING_CONFIRMATION': 'ZVWB6ZFHTQMM0DP7DM2YY50B1VM6',
    'PAYMENT_SUCCESS': '8VJX7RCSSB4Q8PGRMHXBJANMPDQD',
    'SESSION_CONFIRMATION': '5WAKCSPDBGMENWM3V1YQPQ2TN3NR',
    'REMINDER_24H': 'YMY9WGJWAV4D31NMHD60MNSPT5C5',
    'REMINDER_30M': 'E9BV096ASN40SYK6QAYRE0QERAS0',
    'BOOKING_CANCELLED': 'CLIENT_BOOKING_CANCELLED_V1',
    'BOOKING_RESCHEDULED': 'd',  # Note: This appears incomplete in .env
    'CREDIT_PURCHASE': 'CLIENT_CREDIT_PURCHASE_V1',
    'REVIEW_REQUEST': 'CLIENT_REVIEW_REQUEST_V1',
    'PRACTITIONER_MESSAGE': 'CLIENT_PRACTITIONER_MESSAGE_V1',
    'BOOKING_COMPLETED_REVIEW_REQUEST': '6XSJZ0H82V48T7G0Z1EAA60CX1JP',
}

# Practitioner Email Templates
PRACTITIONER_TEMPLATES = {
    'WELCOME': 'FDGB1NTM3MM0W2KPS9J1CM55MQSE',
    'PROFILE_INCOMPLETE': 'SN74R7WK81MQ4VNG8W52GY5RGKHF',
    'NO_SERVICES': 'KMGSN4BJZXM73FQ6Z13MFG5X292T',
    'SERVICE_CREATED': 'PRACTITIONER_SERVICE_CREATED_V1',
    'BUNDLE_CREATED': 'PRACTITIONER_BUNDLE_CREATED_V1',
    'BOOKING_RECEIVED': 'BT6BP63X0S4NQ2NXHAE0R81NZKZ0',
    'BOOKING_CANCELLED': 'PRACTITIONER_BOOKING_CANCELLED_V1',
    'BOOKING_RESCHEDULED': 'DG4A5490GA4A4TG85B05SMRKHHPA',
    'PAYOUT_COMPLETED': 'AF8C60G6NV4NQ4QTCB3K1C2SWG9A',
    'REMINDER_24H': 'ECN1ZFV2TJ4RKMGEVRYJCV182D9Q',
    'REMINDER_30M': 'MZQYMNMYSS4BH5GV2NC8AGPQEC3Z',
    'NEW_REVIEW': 'PRACTITIONER_NEW_REVIEW_V1',
    'EARNINGS_SUMMARY': 'PRACTITIONER_EARNINGS_SUMMARY_V1',
    'CLIENT_MESSAGE': 'PRACTITIONER_CLIENT_MESSAGE_V1',
    'VERIFICATION_APPROVED': 'PRACTITIONER_VERIFICATION_APPROVED_V1',
    'VERIFICATION_REJECTED': 'PRACTITIONER_VERIFICATION_REJECTED_V1',
}

# Helper function to get template IDs with fallback
def get_client_template(template_name):
    """Get client template ID with fallback to template name if not found."""
    return CLIENT_TEMPLATES.get(template_name, f'CLIENT_{template_name}_V1')

def get_practitioner_template(template_name):
    """Get practitioner template ID with fallback to template name if not found."""
    return PRACTITIONER_TEMPLATES.get(template_name, f'PRACTITIONER_{template_name}_V1')