"""
Django settings for estuary project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from . import courier_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rxts$d4^xi5us3dc21bi8o_25if^vd7=idqjnfn(kf+s)behcl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'admin', 'api', 'estuary-backend.onrender.com', '.onrender.com', 'haughty-unbrokenly-merrie.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    "channels",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_celery_beat",
    "django_celery_results",
    
    # Local apps
    "users.apps.UsersConfig",
    "ai_images",
    "analytics",
    "bookings",
    "common",
    "community",
    "emails",
    "integrations",
    "locations",
    "media",
    "messaging",
    "notifications",
    "payments",
    "practitioners",
    "referrals",
    "reviews",
    "rooms",
    "services",
    "streams",
    "utils",
    "workflows",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "estuary.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "estuary.wsgi.application"
ASGI_APPLICATION = "estuary.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use DATABASE_URL if provided, otherwise fall back to individual settings
DATABASES = {
    "default": dj_database_url.config(
        default={
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", default="estuary"),
            "USER": os.getenv("POSTGRES_USER", default="estuary"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", default="estuary"),
            "HOST": os.getenv("POSTGRES_HOST", default="postgres"),
            "PORT": os.getenv("POSTGRES_PORT", default="5432"),
        },
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Path where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_files')

# Get Cloudflare settings with safe defaults
CLOUDFLARE_R2_ACCESS_KEY_ID = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID', '')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '')
CLOUDFLARE_R2_STORAGE_BUCKET_NAME = os.getenv('CLOUDFLARE_R2_STORAGE_BUCKET_NAME', '')
CLOUDFLARE_R2_ENDPOINT_URL = os.getenv('CLOUDFLARE_R2_ENDPOINT_URL', '')
CLOUDFLARE_R2_REGION_NAME = os.getenv('CLOUDFLARE_R2_REGION_NAME', 'auto')
CLOUDFLARE_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN', '')

# Django 4.2+ STORAGES configuration
# Configure default and staticfiles storage
if CLOUDFLARE_R2_ACCESS_KEY_ID and CLOUDFLARE_R2_STORAGE_BUCKET_NAME:
    # Use Cloudflare R2 for media files
    STORAGES = {
        "default": {
            "BACKEND": "integrations.cloudflare_r2.storage.CloudflareR2Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Fallback to local storage if R2 is not configured
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    if not DEBUG:
        import warnings
        warnings.warn("R2 storage not configured in production! Using local filesystem.")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.User'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'messaging': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Django REST Framework configuration
# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'EXCEPTION_HANDLER': 'core.api.exceptions.custom_exception_handler',
    # Temporarily disable versioning to test schema generation
    # 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
    'DATETIME_INPUT_FORMATS': ['%Y-%m-%dT%H:%M:%S.%fZ', '%Y-%m-%dT%H:%M:%SZ'],
}

# DRF Spectacular settings for OpenAPI schema
SPECTACULAR_SETTINGS = {
    'TITLE': 'Estuary API',
    'DESCRIPTION': '''
    # Estuary Wellness Marketplace API
    
    ## Overview
    The Estuary API provides a comprehensive platform for wellness services, connecting practitioners with clients through an intuitive marketplace. Our API supports various service types including sessions, workshops, and courses.
    
    ## Key Features
    - **Practitioner Management**: Complete profile and service management for wellness professionals
    - **Booking System**: Flexible booking for sessions, workshops, and courses
    - **Payment Processing**: Secure payment handling with credit-based system
    - **Real-time Communications**: Video streaming and messaging capabilities
    - **Content Platform**: Support for streaming content and media management
    
    ## Authentication
    All API endpoints require authentication using JWT tokens. Include the token in the Authorization header:
    ```
    Authorization: Bearer <your-token>
    ```
    
    ## Rate Limiting
    - Anonymous users: 100 requests per hour
    - Authenticated users: 1000 requests per hour
    
    ## API Versioning
    The API uses URL-based versioning. Current version: v1
    
    ## Response Format
    All responses are in JSON format with consistent error handling.
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'DISABLE_ERRORS_AND_WARNINGS': False,
    # Remove path prefix since we're now at the API root level
    # Let spectacular auto-discover the paths
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # Authentication configuration
    'SECURITY': [{
        'bearerAuth': []
    }],
    'SECURITY_DEFINITIONS': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
        }
    },
    
    # Component configuration
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    
    # Swagger UI configuration
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'defaultModelRendering': 'example',
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
    },
    
    # ReDoc UI configuration
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'disableSearch': False,
        'expandResponses': '200,201',
        'pathInMiddlePanel': True,
    },
    
    # API tags for organization
    'TAGS': [
        {'name': 'Auth', 'description': 'Authentication and authorization endpoints'},
        {'name': 'Users', 'description': 'User profile and account management'},
        {'name': 'Practitioners', 'description': 'Practitioner profiles, services, and availability'},
        {'name': 'Services', 'description': 'Service catalog including sessions, workshops, and courses'},
        {'name': 'Bookings', 'description': 'Booking creation, management, and scheduling'},
        {'name': 'Availability', 'description': 'Practitioner availability and time slot management'},
        {'name': 'Payments', 'description': 'Payment processing, credits, and transactions'},
        {'name': 'Subscriptions', 'description': 'Practitioner subscription management'},
        {'name': 'Reviews', 'description': 'Reviews and ratings for practitioners and services'},
        {'name': 'Locations', 'description': 'Service locations and venue management'},
        {'name': 'Media', 'description': 'Media upload and management'},
        {'name': 'Messaging', 'description': 'Real-time messaging between users'},
        {'name': 'Notifications', 'description': 'Push notifications and alerts'},
        {'name': 'Streams', 'description': 'Live streaming and video content'},
        {'name': 'Rooms', 'description': 'Video room management for sessions'},
        {'name': 'Community', 'description': 'Community features and interactions'},
        {'name': 'Analytics', 'description': 'Analytics and reporting endpoints'},
        {'name': 'Search', 'description': 'Search practitioners and services'},
        {'name': 'Referrals', 'description': 'Referral program management'},
    ],
    
    # Example value configuration
    'EXAMPLES_TITLE': 'Example',
    'EXAMPLES_DESCRIPTION_KEY': 'description',
    'EXAMPLES_VALUE_KEY': 'value',
    
    # Enable preprocessing hook for debugging
    'PREPROCESSING_HOOKS': [
        'api.v1.schema.preprocessing_filter_spec',
    ],
    # 'POSTPROCESSING_HOOKS': [
    #     'drf_spectacular.hooks.postprocess_schema_enums',
    #     'api.v1.schema.postprocess_schema_responses',
    # ],
    
    # Operation ID generation
    'OPERATION_ID_OVERRIDES': {
        'TokenObtainPairView': 'auth_login',
        'TokenRefreshView': 'auth_refresh',
        'TokenVerifyView': 'auth_verify',
        'TokenBlacklistView': 'auth_logout',
    },
    
    # Contact information
    'CONTACT': {
        'name': 'Estuary API Support',
        'email': 'api@estuary.com',
    },
    
    # License information
    'LICENSE': {
        'name': 'Proprietary',
    },
    
    # External documentation
    'EXTERNAL_DOCS': {
        'description': 'Find more info here',
        'url': 'https://docs.estuary.com',
    },
    
    # Enum name overrides - commented out due to duplication issues
    # 'ENUM_NAME_OVERRIDES': {
    #     'ValidationErrorEnum': 'drf_spectacular.openapi.ValidationError',
    #     'ParseErrorEnum': 'drf_spectacular.openapi.ParseError',
    #     'AuthenticationFailedEnum': 'drf_spectacular.openapi.AuthenticationFailed',
    #     'NotAuthenticatedEnum': 'drf_spectacular.openapi.NotAuthenticated',
    #     'PermissionDeniedEnum': 'drf_spectacular.openapi.PermissionDenied',
    #     'NotFoundEnum': 'drf_spectacular.openapi.NotFound',
    # },
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    # Custom token fields to match existing FastAPI tokens
    'TOKEN_OBTAIN_SERIALIZER': 'users.api.v1.serializers.CustomTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
}

# ============================================================================
# LiveKit Configuration
# ============================================================================

# LiveKit API credentials
LIVEKIT_API_KEY = os.getenv('LIVEKIT_API_KEY', '')
LIVEKIT_API_SECRET = os.getenv('LIVEKIT_API_SECRET', '')
LIVEKIT_HOST = os.getenv('LIVEKIT_HOST', 'https://your-instance.livekit.cloud')

# LiveKit default recording setting
LIVEKIT_DEFAULT_RECORDING_ENABLED = os.getenv('LIVEKIT_DEFAULT_RECORDING_ENABLED', 'False').lower() == 'true'

# LiveKit room defaults
LIVEKIT_ROOM_DEFAULTS = {
    'empty_timeout': 600,  # 10 minutes
    'max_participants': 100,
    'enable_recording': False,  # Practitioner decides per room
    'enable_e2ee': False,  # End-to-end encryption
}

# LiveKit SIP/PSTN configuration (for phone dial-in)
LIVEKIT_SIP_ENABLED = os.getenv('LIVEKIT_SIP_ENABLED', 'False').lower() == 'true'
LIVEKIT_SIP_PROVIDER = os.getenv('LIVEKIT_SIP_PROVIDER', 'twilio')  # twilio, telnyx, vonage
LIVEKIT_SIP_TRUNK_ID = os.getenv('LIVEKIT_SIP_TRUNK_ID', '')
LIVEKIT_SIP_DEFAULT_REGION = os.getenv('LIVEKIT_SIP_DEFAULT_REGION', 'US')

# LiveKit webhook secret (for verifying webhooks)
LIVEKIT_WEBHOOK_SECRET = os.getenv('LIVEKIT_WEBHOOK_SECRET', LIVEKIT_API_SECRET)

# LiveKit recording storage (S3/CloudFlare R2)
LIVEKIT_RECORDING_STORAGE = {
    'type': os.getenv('LIVEKIT_RECORDING_STORAGE_TYPE', 's3'),  # s3, r2, azure
    'bucket': os.getenv('LIVEKIT_RECORDING_BUCKET', 'estuary-recordings'),
    'region': os.getenv('LIVEKIT_RECORDING_REGION', 'us-east-1'),
    'access_key': os.getenv('LIVEKIT_RECORDING_ACCESS_KEY', ''),
    'secret_key': os.getenv('LIVEKIT_RECORDING_SECRET_KEY', ''),
    'endpoint': os.getenv('LIVEKIT_RECORDING_ENDPOINT', ''),  # For R2/MinIO
}

# ============================================================================
# Stripe Configuration
# ============================================================================

# Stripe API keys
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Stripe Connect settings (for practitioner payouts)
STRIPE_CONNECT_CLIENT_ID = os.getenv('STRIPE_CONNECT_CLIENT_ID', '')
STRIPE_CONNECT_WEBHOOK_SECRET = os.getenv('STRIPE_CONNECT_WEBHOOK_SECRET', '')

# Stripe product/price IDs (for fixed products like credit packages)
STRIPE_CREDIT_PACKAGES = {
    '10_credits': os.getenv('STRIPE_PRICE_10_CREDITS', ''),
    '25_credits': os.getenv('STRIPE_PRICE_25_CREDITS', ''),
    '50_credits': os.getenv('STRIPE_PRICE_50_CREDITS', ''),
    '100_credits': os.getenv('STRIPE_PRICE_100_CREDITS', ''),
}

# Stripe settings
STRIPE_CURRENCY = 'usd'
STRIPE_AUTOMATIC_TAX_ENABLED = os.getenv('STRIPE_AUTOMATIC_TAX_ENABLED', 'False').lower() == 'true'
STRIPE_STATEMENT_DESCRIPTOR = 'ESTUARY'

# Frontend URL for redirects
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3001')
# Backend URL for building absolute URLs
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')

# Payment settings
PAYMENT_MINIMUM_AMOUNT_CENTS = 100  # $1.00 minimum
PAYMENT_HOLD_PERIOD_HOURS = 48  # Hold period before practitioner can withdraw
PAYOUT_MINIMUM_AMOUNT_CENTS = 5000  # $50.00 minimum payout

# ============================================================================
# Cloudflare R2 Storage Configuration (moved to media section above)
# ============================================================================

# ============================================================================
# Temporal Configuration
# ============================================================================

TEMPORAL_HOST = os.getenv('TEMPORAL_HOST', 'localhost:7233')
TEMPORAL_NAMESPACE = os.getenv('TEMPORAL_NAMESPACE', 'default')
TEMPORAL_TASK_QUEUE = os.getenv('TEMPORAL_TASK_QUEUE', 'estuary-main')

# Worker configuration
TEMPORAL_MAX_CONCURRENT_ACTIVITIES = int(os.getenv('TEMPORAL_MAX_CONCURRENT_ACTIVITIES', '100'))
TEMPORAL_MAX_CACHED_WORKFLOWS = int(os.getenv('TEMPORAL_MAX_CACHED_WORKFLOWS', '500'))

# ============================================================================
# Django Channels Configuration
# ============================================================================

# Use Redis for channel layer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', 'redis'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# Fallback to in-memory for development without Redis
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }

# ============================================================================
# CORS Configuration
# ============================================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend development
    "http://localhost:3001",  # Frontend development
    "http://localhost:8000",  # API development
    "http://localhost:8001",  # Alternative API port
    "https://estuary-backend.onrender.com",  # Backend on Render
    "https://estuary-frontend.onrender.com",  # Frontend on Render
]

# Allow credentials to be included in CORS requests (for cookies/auth)
CORS_ALLOW_CREDENTIALS = True

# Headers that can be used during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================================================
# Security Settings
# ============================================================================

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# ============================================================================
# Celery Configuration
# ============================================================================

# Celery broker URL (Redis)
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # Use Django database for task results

# Celery settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_RESULT_PERSISTENT = True   # Keep results in database

# Task execution settings
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_DISABLE_RATE_LIMITS = False

# Beat settings (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_COMPRESSION = 'gzip'

# Task routing (optional - for scaling)
CELERY_TASK_ROUTES = {
    'notifications.tasks.*': {'queue': 'notifications'},
    'notifications.cron.*': {'queue': 'notifications'},  # Add cron tasks to notifications queue
    'payments.tasks.*': {'queue': 'payments'},
    'bookings.tasks.*': {'queue': 'default'},
}

# Celery Flower settings (monitoring)
FLOWER_PORT = os.environ.get('FLOWER_PORT', 5555)
FLOWER_BASIC_AUTH = os.environ.get('FLOWER_BASIC_AUTH', '')  # username:password

# ============================================================================
# Courier Configuration
# ============================================================================

COURIER_AUTH_TOKEN = os.environ.get('COURIER_AUTH_TOKEN', '')

# Courier Template IDs from config file
COURIER_CLIENT_WELCOME_TEMPLATE = courier_config.CLIENT_TEMPLATES['WELCOME']
COURIER_CLIENT_EMAIL_VERIFICATION_TEMPLATE = courier_config.CLIENT_TEMPLATES['EMAIL_VERIFICATION']
COURIER_CLIENT_BOOKING_CONFIRMATION_TEMPLATE = courier_config.CLIENT_TEMPLATES['BOOKING_CONFIRMATION']
COURIER_CLIENT_PAYMENT_SUCCESS_TEMPLATE = courier_config.CLIENT_TEMPLATES['PAYMENT_SUCCESS']
COURIER_CLIENT_SESSION_CONFIRMATION_TEMPLATE = courier_config.CLIENT_TEMPLATES['SESSION_CONFIRMATION']
COURIER_CLIENT_REMINDER_24H_TEMPLATE = courier_config.CLIENT_TEMPLATES['REMINDER_24H']
COURIER_CLIENT_REMINDER_30M_TEMPLATE = courier_config.CLIENT_TEMPLATES['REMINDER_30M']
COURIER_CLIENT_BOOKING_RESCHEDULED_TEMPLATE = courier_config.CLIENT_TEMPLATES['BOOKING_RESCHEDULED']
COURIER_CLIENT_BOOKING_CANCELLED_TEMPLATE = courier_config.CLIENT_TEMPLATES['BOOKING_CANCELLED']
COURIER_CLIENT_CREDIT_PURCHASE_TEMPLATE = courier_config.CLIENT_TEMPLATES['CREDIT_PURCHASE']
COURIER_CLIENT_REVIEW_REQUEST_TEMPLATE = courier_config.CLIENT_TEMPLATES['REVIEW_REQUEST']
COURIER_CLIENT_PRACTITIONER_MESSAGE_TEMPLATE = courier_config.CLIENT_TEMPLATES['PRACTITIONER_MESSAGE']
COURIER_CLIENT_BOOKING_COMPLETED_REVIEW_REQUEST_TEMPLATE = courier_config.CLIENT_TEMPLATES['BOOKING_COMPLETED_REVIEW_REQUEST']

COURIER_PRACTITIONER_WELCOME_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['WELCOME']
COURIER_PRACTITIONER_PROFILE_INCOMPLETE_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['PROFILE_INCOMPLETE']
COURIER_PRACTITIONER_NO_SERVICES_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['NO_SERVICES']
COURIER_PRACTITIONER_BOOKING_RECEIVED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['BOOKING_RECEIVED']
COURIER_PRACTITIONER_BOOKING_CANCELLED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['BOOKING_CANCELLED']
COURIER_PRACTITIONER_BOOKING_RESCHEDULED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['BOOKING_RESCHEDULED']
COURIER_PRACTITIONER_SERVICE_CREATED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['SERVICE_CREATED']
COURIER_PRACTITIONER_BUNDLE_CREATED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['BUNDLE_CREATED']
COURIER_PRACTITIONER_PAYOUT_COMPLETED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['PAYOUT_COMPLETED']
COURIER_PRACTITIONER_REMINDER_24H_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['REMINDER_24H']
COURIER_PRACTITIONER_REMINDER_30M_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['REMINDER_30M']
COURIER_PRACTITIONER_NEW_REVIEW_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['NEW_REVIEW']
COURIER_PRACTITIONER_EARNINGS_SUMMARY_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['EARNINGS_SUMMARY']
COURIER_PRACTITIONER_CLIENT_MESSAGE_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['CLIENT_MESSAGE']
COURIER_PRACTITIONER_VERIFICATION_APPROVED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['VERIFICATION_APPROVED']
COURIER_PRACTITIONER_VERIFICATION_REJECTED_TEMPLATE = courier_config.PRACTITIONER_TEMPLATES['VERIFICATION_REJECTED']

# Frontend URL for email links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3001')
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'support@estuary.app')
APP_NAME = 'Estuary'

# ============================================================================
# Resend Email Configuration (New System)
# ============================================================================

RESEND_API = os.environ.get('RESEND_API', '')
EMAIL_LOGO_URL = os.environ.get('EMAIL_LOGO_URL', 'https://estuary.com/logo.png')
WEBSITE_URL = os.environ.get('WEBSITE_URL', FRONTEND_URL)  # Use FRONTEND_URL as default