# Generated by Django 5.1.3 on 2026-03-26 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0023_performance_indexes'),
        ('common', '0007_initial'),
        ('practitioners', '0011_add_answer_to_question'),
        ('services', '0027_add_session_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('form_type', models.CharField(choices=[('intake', 'Intake Questionnaire'), ('consent', 'Consent Form')], max_length=20)),
                ('is_platform_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('modality', models.ForeignKey(blank=True, help_text='Suggested modality for this template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.modality')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='practitioners.practitioner')),
            ],
            options={
                'ordering': ['-is_platform_template', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('scale', 'Scale (1-10)'), ('date', 'Date'), ('file_upload', 'File Upload')], max_length=20)),
                ('label', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text="Options for choice questions: ['Option A', 'Option B']", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intake.formtemplate')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('legal_text', models.TextField(help_text='Full consent/waiver text')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='intake.formtemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='IntakeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public UUID for API exposure', unique=True)),
                ('responses', models.JSONField(help_text="Answers keyed by question ID: {'123': 'answer'}")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_prefilled', models.BooleanField(default=False, help_text='True if carried from a previous booking')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_responses', to='bookings.booking')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intake.formtemplate')),
                ('previous_response', models.ForeignKey(blank=True, help_text='Previous response this was pre-filled from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.intakeresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False, help_text='If True and consent form, blocks room entry')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='intake.formtemplate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConsentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_name', models.CharField(help_text='Typed name as e-signature', max_length=255)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_signatures', to='bookings.booking')),
                ('consent_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='intake.consentdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['booking', 'user'], name='intake_cons_booking_28e47e_idx'), models.Index(fields=['consent_document'], name='intake_cons_consent_9e6bdc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['practitioner', 'form_type', 'is_active'], name='intake_form_practit_ee5f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['is_platform_template', 'form_type'], name='intake_form_is_plat_669644_idx'),
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['template', 'order'], name='intake_form_templat_a946de_idx'),
        ),
        migrations.AddIndex(
            model_name='consentdocument',
            index=models.Index(fields=['template', '-version'], name='intake_cons_templat_fcc36d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentdocument',
            unique_together={('template', 'version')},
        ),
        migrations.AddIndex(
            model_name='intakeresponse',
            index=models.Index(fields=['booking', 'form_template'], name='intake_inta_booking_1f47d5_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeresponse',
            index=models.Index(fields=['user', '-submitted_at'], name='intake_inta_user_id_625b71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceform',
            unique_together={('service', 'form_template')},
        ),
    ]
