# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="service_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="services.servicesession",
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["parent"], name="service_cat_parent__213179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_active"], name="service_cat_is_acti_c27f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["slug"], name="service_cat_slug_192b5a_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["practitioner"], name="service_cat_practit_98aaa1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicepractitioner",
            unique_together={("service", "practitioner")},
        ),
        migrations.AlterUniqueTogether(
            name="servicerelationship",
            unique_together={("parent_service", "child_service")},
        ),
        migrations.AlterUniqueTogether(
            name="servicesession",
            unique_together={("service", "start_time")},
        ),
        migrations.AddConstraint(
            model_name="servicebenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service__isnull", False),
                    ("session__isnull", False),
                    _connector="OR",
                ),
                name="service_or_session_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicebenefit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("service", "order"),
                name="unique_service_benefit_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicebenefit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("session", "order"),
                name="unique_session_benefit_order",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["practitioner"], name="services_practit_137bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_type"], name="services_service_3bbaa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["category"], name="services_categor_a61a21_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active"], name="services_is_acti_b1f5d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_featured"], name="services_is_feat_f920c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["experience_level"], name="services_experie_61847d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="waitlist",
            index=models.Index(fields=["service"], name="waitlists_service_86d078_idx"),
        ),
        migrations.AddIndex(
            model_name="waitlist",
            index=models.Index(
                fields=["service_session"], name="waitlists_service_b45b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitlist",
            index=models.Index(fields=["user"], name="waitlists_user_id_906ab3_idx"),
        ),
        migrations.AddIndex(
            model_name="waitlist",
            index=models.Index(fields=["status"], name="waitlists_status_2edb70_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="waitlist",
            unique_together={("service", "user"), ("service_session", "user")},
        ),
    ]
