# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='service_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.servicesession'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='servicepractitioner',
            unique_together={('service', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='servicerelationship',
            unique_together={('parent_service', 'child_service')},
        ),
        migrations.AlterUniqueTogether(
            name='servicesession',
            unique_together={('service', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='servicebenefit',
            constraint=models.CheckConstraint(condition=models.Q(('service__isnull', False), ('session__isnull', False), _connector='OR'), name='service_or_session_required'),
        ),
        migrations.AddConstraint(
            model_name='servicebenefit',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('service', 'order'), name='unique_service_benefit_order'),
        ),
        migrations.AddConstraint(
            model_name='servicebenefit',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'order'), name='unique_session_benefit_order'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['code'], name='services_se_code_09efd4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['is_active', 'order'], name='services_se_is_acti_9607ae_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='services_se_service_57f6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_se_categor_7ca2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='services_se_is_feat_35b40d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['experience_level'], name='services_se_experie_b45ddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service__isnull', False), ('session__isnull', True)), models.Q(('service__isnull', True), ('session__isnull', False)), _connector='OR'), name='agenda_item_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('service', 'order'), name='unique_service_agenda_item_order'),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'order'), name='unique_session_agenda_item_order'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['service'], name='waitlists_service_86d078_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['service_session'], name='waitlists_service_b45b98_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['user'], name='waitlists_user_id_906ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['status'], name='waitlists_status_2edb70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('service', 'user'), ('service_session', 'user')},
        ),
    ]
