# Generated by Django 5.1.7 on 2025-04-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="practitioner",
        ),
        migrations.RemoveField(
            model_name="parentservicecategoryrelation",
            name="category",
        ),
        migrations.RemoveField(
            model_name="servicecategoryrelation",
            name="category",
        ),
        migrations.RemoveField(
            model_name="parentservicecategoryrelation",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicecategoryrelation",
            name="service",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="services_practit_137bac_idx",
        ),
        migrations.RemoveField(
            model_name="service",
            name="physical_location",
        ),
        migrations.RemoveField(
            model_name="service",
            name="practitioner",
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ParentServiceCategoryRelation",
        ),
        migrations.DeleteModel(
            name="ServiceCategoryRelation",
        ),
    ]
