# Generated by Django 5.1.3 on 2025-06-11 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_practitionerservicecategory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='practitionerservicecategory',
            new_name='services_pr_practit_a61372_idx',
            old_name='services_pr_practit_b7e8e3_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionerservicecategory',
            new_name='services_pr_practit_0e709b_idx',
            old_name='services_pr_practit_97a4e4_idx',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Global category for discovery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
    ]
