# Generated by Django 5.1.7 on 2025-04-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_category_practitioner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionagendaitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='services.service'),
        ),
        migrations.AlterField(
            model_name='sessionagendaitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionagendaitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='services.servicesession'),
        ),
        migrations.AlterField(
            model_name='sessionagendaitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service__isnull', False), ('session__isnull', True)), models.Q(('service__isnull', True), ('session__isnull', False)), _connector='OR'), name='agenda_item_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('service', 'order'), name='unique_service_agenda_item_order'),
        ),
        migrations.AddConstraint(
            model_name='sessionagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'order'), name='unique_session_agenda_item_order'),
        ),
    ]
