# Generated by Django 5.1.3 on 2025-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_services_pr_practit_b7e8e3_idx_services_pr_practit_a61372_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', help_text='Service publication status', max_length=20),
        ),
    ]
