# Generated by Django 5.1.8 on 2025-05-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_sessionagendaitem_service_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_service_57f6a4_idx',
            old_name='services_service_3bbaa2_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_categor_7ca2f8_idx',
            old_name='services_categor_a61a21_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_is_acti_91b7ea_idx',
            old_name='services_is_acti_b1f5d3_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_is_feat_35b40d_idx',
            old_name='services_is_feat_f920c3_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_experie_b45ddc_idx',
            old_name='services_experie_61847d_idx',
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicepractitioner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table=None,
        ),
    ]
