# Generated by Django 5.1.3 on 2025-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_change_image_url_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service cover image', null=True, upload_to='services/images/%Y/%m/'),
        ),
    ]
