# Generated by Django 5.1.3 on 2025-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0003_practitioner_slug_and_more'),
        ('services', '0010_add_schedule_field'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_service_57f6a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_categor_7ca2f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_is_acti_91b7ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_is_feat_35b40d_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='services_se_service_fc36b8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['primary_practitioner', 'is_active'], name='services_se_primary_796372_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_se_categor_b50c86_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['location_type'], name='services_se_locatio_f215ad_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price_cents'], name='services_se_price_c_bc23f1_idx'),
        ),
    ]
