# Generated by Django 5.1.3 on 2025-11-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_modality_is_featured_modality_slug_and_more'),
        ('services', '0013_make_service_slug_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='modalities',
            field=models.ManyToManyField(blank=True, help_text='Treatment modalities for this service (e.g., Yoga, Meditation)', related_name='services', to='common.modality'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use modalities instead. Global category for discovery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory'),
        ),
    ]
