# Generated by Django 5.1.3 on 2025-11-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('services', '0014_service_modalities_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='practitioner_location',
            field=models.ForeignKey(blank=True, help_text='Practitioner location where this service is offered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='locations.practitionerlocation'),
        ),
    ]
