# Generated by Django 5.1.3 on 2025-11-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('services', '0015_remove_service_address_service_practitioner_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesession',
            name='address',
        ),
        migrations.AddField(
            model_name='servicesession',
            name='practitioner_location',
            field=models.ForeignKey(blank=True, help_text='Practitioner location where this session takes place (for in-person sessions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='locations.practitionerlocation'),
        ),
    ]
