# Generated by Django 5.1.3 on 2025-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_create_servicesessions_for_existing_bookings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicesession',
            new_name='service_ses_service_c06988_idx',
            old_name='service_ses_service_idx',
        ),
        migrations.RenameIndex(
            model_name='servicesession',
            new_name='service_ses_session_0c7f6b_idx',
            old_name='service_ses_type_vis_idx',
        ),
        migrations.RenameIndex(
            model_name='servicesession',
            new_name='service_ses_visibil_2bad45_idx',
            old_name='service_ses_vis_time_idx',
        ),
        migrations.RenameIndex(
            model_name='servicesession',
            new_name='service_ses_status_fd8bd0_idx',
            old_name='service_ses_status_time_idx',
        ),
        migrations.AlterField(
            model_name='servicesession',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='For ordering course sessions'),
        ),
    ]
