# Generated by Django 5.1.3 on 2025-11-21 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_add_actual_times_remove_room_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesession',
            name='last_rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='When this session was last rescheduled', null=True),
        ),
        migrations.AddField(
            model_name='servicesession',
            name='original_end_time',
            field=models.DateTimeField(blank=True, help_text='Original end time before any rescheduling (preserved for history)', null=True),
        ),
        migrations.AddField(
            model_name='servicesession',
            name='original_start_time',
            field=models.DateTimeField(blank=True, help_text='Original start time before any rescheduling (preserved for history)', null=True),
        ),
        migrations.AddField(
            model_name='servicesession',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this session has been rescheduled'),
        ),
        migrations.AddField(
            model_name='servicesession',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, help_text='Who last rescheduled this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
