# Generated by Django 5.1.3 on 2025-11-22 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_status_architecture_refactor'),
        ('services', '0024_add_reschedule_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total time in session (seconds)'),
        ),
        migrations.AlterField(
            model_name='servicesession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', help_text='Lifecycle status of the session (draft/scheduled/in_progress/completed/canceled)', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='attendance_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked In'), ('attended', 'Attended'), ('no_show', 'No Show'), ('partial', 'Partial')], default='registered', help_text='Tracks whether the user attended the session', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='When user joined the session', null=True),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='When user left the session', null=True),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'attendance_status'], name='session_par_session_cfa023_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['user', 'attendance_status'], name='session_par_user_id_db0110_idx'),
        ),
    ]
