# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('service_views', models.PositiveIntegerField(default=0)),
                ('bookings_received', models.PositiveIntegerField(default=0)),
                ('bookings_completed', models.PositiveIntegerField(default=0)),
                ('bookings_cancelled', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews_received', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'practitioner_performance',
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=255)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_results', models.PositiveIntegerField(default=0)),
                ('conversion', models.BooleanField(default=False)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'search_analytics',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('search_type', models.CharField(default='all', max_length=20)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('clicked_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_logs',
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('cancellations', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'service_analytics',
            },
        ),
        migrations.CreateModel(
            name='ServiceView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_views',
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('logins', models.PositiveIntegerField(default=0)),
                ('session_duration_seconds', models.PositiveIntegerField(default=0)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('searches_performed', models.PositiveIntegerField(default=0)),
                ('bookings_viewed', models.PositiveIntegerField(default=0)),
                ('practitioners_viewed', models.PositiveIntegerField(default=0)),
                ('services_viewed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'user_engagement',
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_reports',
                'indexes': [models.Index(fields=['report_type'], name='financial_r_report__0401ed_idx'), models.Index(fields=['start_date', 'end_date'], name='financial_r_start_d_c34429_idx')],
            },
        ),
    ]
