# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceanalytics',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.service'),
        ),
        migrations.AddField(
            model_name='serviceview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='services.service'),
        ),
        migrations.AddField(
            model_name='serviceview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='practitionerperformance',
            index=models.Index(fields=['date'], name='practitione_date_ec9c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerperformance',
            index=models.Index(fields=['practitioner', 'date'], name='practitione_practit_dfd7f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practitionerperformance',
            unique_together={('practitioner', 'date')},
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['search_date'], name='search_anal_search__165a25_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['user'], name='search_anal_user_id_20bbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query_text'], name='search_anal_query_t_c5f2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at'], name='search_logs_created_1842c5_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user'], name='search_logs_user_id_57f35c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query'], name='search_logs_query_5b6409_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_type'], name='search_logs_search__73ec53_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceanalytics',
            index=models.Index(fields=['date'], name='service_ana_date_9ccf02_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceanalytics',
            index=models.Index(fields=['service', 'date'], name='service_ana_service_a7979e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceanalytics',
            unique_together={('service', 'date')},
        ),
        migrations.AddIndex(
            model_name='serviceview',
            index=models.Index(fields=['service', 'viewed_at'], name='service_vie_service_40a6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceview',
            index=models.Index(fields=['user'], name='service_vie_user_id_4e82af_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceview',
            index=models.Index(fields=['viewed_at'], name='service_vie_viewed__47f4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['date'], name='user_engage_date_d2d54b_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user', 'date'], name='user_engage_user_id_9c9dbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagement',
            unique_together={('user', 'date')},
        ),
    ]
