# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("country", models.CharField(unique=True)),
                ("country_code", models.CharField()),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO language code (e.g., 'en', 'es', 'fr')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the language in its native form",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modality",
                "verbose_name_plural": "Modalities",
                "db_table": "modalities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("country_code", models.CharField()),
                ("holiday", models.CharField()),
                ("date", models.DateField()),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="utils.country",
                        to_field="country",
                    ),
                ),
            ],
            options={
                "db_table": "holidays",
            },
        ),
    ]
