# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full country name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('code_3', models.CharField(help_text='ISO 3166-1 alpha-3 country code', max_length=3, unique=True)),
                ('numeric_code', models.CharField(blank=True, help_text='ISO 3166-1 numeric code', max_length=3, null=True)),
                ('phone_code', models.CharField(blank=True, help_text='International dialing code', max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code', max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='utils_count_code_51d331_idx'), models.Index(fields=['is_active'], name='utils_count_is_acti_aee6f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='English name of the language', max_length=100)),
                ('native_name', models.CharField(blank=True, help_text='Name of the language in its native form', max_length=100, null=True)),
                ('code', models.CharField(help_text="ISO 639-1 language code (e.g., 'en', 'es', 'fr')", max_length=10, unique=True)),
                ('code_3', models.CharField(blank=True, help_text='ISO 639-3 language code', max_length=3, null=True)),
                ('is_rtl', models.BooleanField(default=False, help_text='Whether language is right-to-left')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='utils_langu_code_d697a4_idx'), models.Index(fields=['is_active', 'order'], name='utils_langu_is_acti_ee8187_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('clinic', 'Clinic'), ('studio', 'Studio'), ('online', 'Online Only'), ('other', 'Other')], default='office', max_length=20)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'indexes': [models.Index(fields=['city', 'state_province'], name='utils_locat_city_f4bc35_idx'), models.Index(fields=['country_code'], name='utils_locat_country_7c5bce_idx'), models.Index(fields=['latitude', 'longitude'], name='utils_locat_latitud_1bfd58_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Holiday name', max_length=255)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this holiday recurs annually')),
                ('is_business_day', models.BooleanField(default=False, help_text='Whether businesses typically remain open')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='utils.country')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['country', 'date'], name='utils_holid_country_d68b39_idx'), models.Index(fields=['date'], name='utils_holid_date_4cc392_idx')],
                'unique_together': {('country', 'name', 'date')},
            },
        ),
    ]
