# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='English name of the language', max_length=100)),
                ('native_name', models.CharField(blank=True, help_text='Name of the language in its native form', max_length=100, null=True)),
                ('code', models.CharField(help_text="ISO 639-1 language code (e.g., 'en', 'es', 'fr')", max_length=10, unique=True)),
                ('code_3', models.CharField(blank=True, help_text='ISO 639-3 language code', max_length=3, null=True)),
                ('is_rtl', models.BooleanField(default=False, help_text='Whether language is right-to-left')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='utils_langu_code_d697a4_idx'), models.Index(fields=['is_active', 'order'], name='utils_langu_is_acti_ee8187_idx')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(help_text='State, province, or region', max_length=100)),
                ('state_province_code', models.CharField(blank=True, help_text="e.g., 'CA', 'ON', 'NSW'", max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('city_slug', models.SlugField(blank=True, max_length=100)),
                ('state_slug', models.SlugField(blank=True, max_length=100)),
                ('metro_area', models.CharField(blank=True, help_text="e.g., 'San Francisco Bay Area', 'Greater NYC'", max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('clinic', 'Clinic'), ('studio', 'Studio'), ('online', 'Online Only'), ('other', 'Other')], default='office', max_length=20)),
                ('active_service_count', models.PositiveIntegerField(default=0, help_text='Number of active services at this location')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='locations.country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['city', 'state_province'], name='utils_addre_city_b06743_idx'), models.Index(fields=['state_province'], name='utils_addre_state_p_48b00f_idx'), models.Index(fields=['postal_code'], name='utils_addre_postal__a7f279_idx'), models.Index(fields=['country_code'], name='utils_addre_country_5f444c_idx'), models.Index(fields=['latitude', 'longitude'], name='utils_addre_latitud_74ab4b_idx'), models.Index(fields=['is_verified'], name='utils_addre_is_veri_567fc4_idx'), models.Index(fields=['metro_area'], name='utils_addre_metro_a_44dfc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Holiday name', max_length=255)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this holiday recurs annually')),
                ('is_business_day', models.BooleanField(default=False, help_text='Whether businesses typically remain open')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='locations.country')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['country', 'date'], name='utils_holid_country_d68b39_idx'), models.Index(fields=['date'], name='utils_holid_date_4cc392_idx')],
                'unique_together': {('country', 'name', 'date')},
            },
        ),
    ]
