# Generated by Django 5.1.3 on 2025-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_livestream_livestreamanalytics_livestreamviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stripe_entry_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for entry tier monthly subscription', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stripe_premium_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for premium tier monthly subscription', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID for this stream', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streamsubscription',
            name='price_cents',
            field=models.IntegerField(default=0, help_text='The actual price being paid monthly (captures price at subscription time)'),
        ),
        migrations.AddField(
            model_name='streamsubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='The Stripe Price ID this subscription is using', max_length=255, null=True),
        ),
    ]
