# Generated by Django 5.1.3

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0006_remove_old_media_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='streams.streampost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_stream_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='streampostsave',
            index=models.Index(fields=['user', 'created_at'], name='streams_str_user_id_cd7c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='streampostsave',
            index=models.Index(fields=['post'], name='streams_str_post_id_6fe4d9_idx'),
        ),
    ]