# Generated by Django 5.1.3 on 2025-07-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_remove_livestream_models'),
        ('streams', '0007_add_stream_post_save'),
    ]

    operations = [
    ]
