# Generated by Django 5.1.3 on 2025-11-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_merge_20250706_0656'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='streampostsave',
            new_name='streams_str_user_id_6a9934_idx',
            old_name='streams_str_user_id_cd7c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='streampostsave',
            new_name='streams_str_post_id_c56fed_idx',
            old_name='streams_str_post_id_6fe4d9_idx',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='stream',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Stream cover image (stored in R2)', null=True, upload_to='streams/covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Stream profile image (stored in R2)', null=True, upload_to='streams/profiles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='streampostmedia',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
