# Generated by Django 5.1.3 on 2026-03-24 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_add_linked_service_to_streampost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='streampostview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_view_per_user_per_post'),
        ),
    ]
