# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerlocation',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locations.country'),
        ),
        migrations.AddField(
            model_name='practitionerlocation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state'),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='locations.city'),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='locations.country'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'is_active'], name='locations_s_country_436f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='locations_s_code_f8d7d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'slug')},
        ),
        migrations.AddIndex(
            model_name='practitionerlocation',
            index=models.Index(fields=['practitioner', 'is_primary'], name='locations_p_practit_610658_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerlocation',
            index=models.Index(fields=['city', 'is_in_person'], name='locations_p_city_id_e1dfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'is_active'], name='locations_c_state_i_837821_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['metro_area'], name='locations_c_metro_a_8c2a84_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_major', 'is_active'], name='locations_c_is_majo_da791e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'slug')},
        ),
        migrations.AddIndex(
            model_name='zipcode',
            index=models.Index(fields=['country', 'code'], name='locations_z_country_43f98a_idx'),
        ),
    ]
