# Generated by Django 5.1.3 on 2025-11-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0010_add_feature_request_model'),
        ('services', '0016_remove_servicesession_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text='Original prompt from practitioner')),
                ('full_prompt', models.TextField(help_text='Complete prompt sent to AI (includes brand guidelines)')),
                ('image', models.ImageField(help_text='Generated image file', upload_to='ai_generated/%Y/%m/')),
                ('model_used', models.CharField(default='gemini-2.5-flash-image', help_text='AI model version used', max_length=100)),
                ('generation_time_seconds', models.FloatField(blank=True, help_text='Time taken to generate image', null=True)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether practitioner used this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When image was applied to a service', null=True)),
                ('practitioner', models.ForeignKey(help_text='Practitioner who generated this image', on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='practitioners.practitioner')),
                ('service', models.ForeignKey(blank=True, help_text='Service this image was applied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['practitioner', '-created_at'], name='ai_images_g_practit_1eb59c_idx'), models.Index(fields=['service'], name='ai_images_g_service_820e05_idx')],
            },
        ),
    ]
