# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewanswer",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="reviews.reviewquestion",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["practitioner"], name="reviews_practit_3e774e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["service"], name="reviews_service_2adf55_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="reviews_user_id_79db63_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["booking"], name="reviews_booking_012755_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="reviews_created_53b5d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rating_17e8a4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewanswer",
            unique_together={("review", "question")},
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["review"], name="review_repo_review__018a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["is_resolved"], name="review_repo_is_reso_87a42f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewreport",
            unique_together={("review", "user")},
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(
                fields=["review"], name="review_vote_review__b8b80c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(fields=["user"], name="review_vote_user_id_3abe31_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together={("review", "user")},
        ),
    ]
