# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.review'),
        ),
        migrations.AddIndex(
            model_name='reviewquestion',
            index=models.Index(fields=['is_active', 'order'], name='reviews_rev_is_acti_6543e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewquestion',
            index=models.Index(fields=['applies_to'], name='reviews_rev_applies_31f298_idx'),
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.reviewquestion'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['practitioner', 'is_published'], name='reviews_rev_practit_f0c269_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['service', 'is_published'], name='reviews_rev_service_7c9b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='reviews_rev_booking_3929ad_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_published'], name='reviews_rev_rating_ad01b8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified', 'is_published'], name='reviews_rev_is_veri_8c5ec6_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='reviews_review_rating_range'),
        ),
        migrations.AddIndex(
            model_name='reviewanswer',
            index=models.Index(fields=['review'], name='reviews_rev_review__608f80_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewanswer',
            index=models.Index(fields=['question'], name='reviews_rev_questio_5bd643_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewanswer',
            unique_together={('review', 'question')},
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review'], name='reviews_rev_review__27ae74_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['is_resolved', 'created_at'], name='reviews_rev_is_reso_735411_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['reason'], name='reviews_rev_reason_dbc9f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['review', 'is_helpful'], name='reviews_rev_review__a1a2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_8bdf16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
