# Generated by Django 5.1.8 on 2025-05-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_practit_0f742b_idx',
            old_name='reviews_practit_3e774e_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_service_1b4478_idx',
            old_name='reviews_service_2adf55_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_user_id_a65d48_idx',
            old_name='reviews_user_id_79db63_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_booking_3929ad_idx',
            old_name='reviews_booking_012755_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_created_bdcc91_idx',
            old_name='reviews_created_53b5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_rating_2db6dd_idx',
            old_name='reviews_rating_17e8a4_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewreport',
            new_name='reviews_rev_review__27ae74_idx',
            old_name='review_repo_review__018a02_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewreport',
            new_name='reviews_rev_is_reso_d36d0a_idx',
            old_name='review_repo_is_reso_87a42f_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewvote',
            new_name='reviews_rev_review__163e87_idx',
            old_name='review_vote_review__b8b80c_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewvote',
            new_name='reviews_rev_user_id_8bdf16_idx',
            old_name='review_vote_user_id_3abe31_idx',
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewanswer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewquestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewvote',
            table=None,
        ),
    ]
