# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_practitioner_responsible', models.BooleanField(default=False, help_text='If True, this fee is deducted from practitioner earnings')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_service_fees',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public UUID for API exposure', unique=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('credits', 'Credits'), ('manual', 'Manual')], default='stripe', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=200)),
                ('subtotal_amount_cents', models.IntegerField(help_text='Subtotal in cents', validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount_cents', models.IntegerField(default=0, help_text='Tax amount in cents', validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_applied_cents', models.IntegerField(default=0, help_text='Credits applied in cents', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount_cents', models.IntegerField(help_text='Total amount in cents', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('order_type', models.CharField(choices=[('direct', 'Direct Service Purchase'), ('credit', 'Credit Purchase'), ('package', 'Package Purchase'), ('subscription', 'Subscription')], default='direct', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tax_details', models.JSONField(blank=True, default=dict)),
                ('audit_log', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('payout_processed', models.BooleanField(default=False)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payout_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('total_paid_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'package_completion_records',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_method_id', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('diners', 'Diners Club'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PractitionerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_balance_cents', models.IntegerField(default=0, help_text='Earnings not yet eligible for payout in cents')),
                ('available_balance_cents', models.IntegerField(default=0, help_text='Earnings ready for payout in cents')),
                ('lifetime_earnings_cents', models.IntegerField(default=0, help_text='Total earnings ever in cents')),
                ('lifetime_payouts_cents', models.IntegerField(default=0, help_text='Total amount paid out in cents')),
                ('last_payout_date', models.DateTimeField(blank=True, help_text='When last payout was processed', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PractitionerPayout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('credits_payout_cents', models.IntegerField(blank=True, help_text='Payout amount in cents', null=True)),
                ('cash_payout_cents', models.IntegerField(blank=True, help_text='Cash payout in cents', null=True)),
                ('commission_collected_cents', models.IntegerField(blank=True, help_text='Commission collected in cents', null=True)),
                ('stripe_account_id', models.TextField(blank=True, null=True)),
                ('stripe_transfer_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(default='stripe', help_text='Method used for payout (e.g., stripe, manual)', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transaction_fee_cents', models.IntegerField(blank=True, help_text='Transaction fee in cents', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PractitionerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_annual', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'practitioner_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base commission rate as a percentage (e.g., 15.00 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_type_commissions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_tiers',
                'ordering': ['order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TierCommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Adjustment to base rate in percentage points (e.g., -5.00 reduces rate by 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tier_commission_adjustments',
            },
        ),
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_cents', models.IntegerField(default=0, help_text='Balance in cents', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.IntegerField(help_text='Amount in cents. Positive for credits added, negative for credits consumed')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('bonus', 'Bonus'), ('transfer', 'Transfer'), ('expiry', 'Expiry')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate if currency conversion was applied', max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EarningsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount_cents', models.IntegerField(help_text='Service price before commission in cents')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage', max_digits=5)),
                ('commission_amount_cents', models.IntegerField(help_text='Commission amount deducted in cents')),
                ('net_amount_cents', models.IntegerField(help_text='Amount practitioner receives in cents')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('available_after', models.DateTimeField(help_text='When funds become available for payout')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(default='booking_completion', help_text='Type of earning (booking_completion, bonus, adjustment)', max_length=50)),
                ('external_fees', models.JSONField(blank=True, help_text='External fees applied (Stripe, Daily.co, etc.)', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_transactions', to='bookings.booking')),
            ],
        ),
    ]
