# Generated by Django 5.1.3 on 2025-06-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions_as_practitioner', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='reference_transaction',
            field=models.ForeignKey(blank=True, help_text='Link to original transaction for refunds/adjustments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.credittransaction'),
        ),
    ]
