# Generated by Django 5.1.3 on 2025-06-10 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_initial'),
        ('payments', '0003_initial'),
        ('practitioners', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagecompletionrecord',
            name='package_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerearnings',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_balance', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerpayout',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerpayout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earningstransaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_transactions', to='payments.practitionerpayout'),
        ),
        migrations.AddField(
            model_name='practitionersubscription',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='servicetypecommission',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='services.servicetype'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontier',
            index=models.Index(fields=['is_active'], name='subscriptio_is_acti_a7d112_idx'),
        ),
        migrations.AddField(
            model_name='practitionersubscription',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='payments.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='tiercommissionadjustment',
            name='service_type_commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_adjustments', to='payments.servicetypecommission'),
        ),
        migrations.AddField(
            model_name='tiercommissionadjustment',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to='payments.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credit_transactions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credit_transactions', to='payments.order'),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credit_transactions_as_practitioner', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='reference_transaction',
            field=models.ForeignKey(blank=True, help_text='Link to original transaction for refunds/adjustments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usercredittransaction'),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credit_transactions', to='services.service'),
        ),
        migrations.AddField(
            model_name='usercredittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.usercredittransaction'),
        ),
        migrations.AddIndex(
            model_name='externalservicefee',
            index=models.Index(fields=['service_type'], name='external_se_service_e6217f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalservicefee',
            index=models.Index(fields=['is_active'], name='external_se_is_acti_02b508_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='payments_or_user_id_f610cb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['practitioner', 'created_at'], name='payments_or_practit_1655d9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='payments_or_status_99bb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='payments_or_order_t_f61db5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_or_stripe__94121c_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_cents__gte', 0)), name='payments_order_total_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='packagecompletionrecord',
            index=models.Index(fields=['package_booking'], name='package_com_package_2c7b95_idx'),
        ),
        migrations.AddIndex(
            model_name='packagecompletionrecord',
            index=models.Index(fields=['status'], name='package_com_status_2e2c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='packagecompletionrecord',
            index=models.Index(fields=['payout_processed'], name='package_com_payout__37af23_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payments_pa_user_id_bd2d73_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['stripe_payment_method_id'], name='payments_pa_stripe__ffc15c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='payments_pa_user_id_61fd94_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='payments_paymentmethod_one_default_per_user'),
        ),
        migrations.AddIndex(
            model_name='practitionerearnings',
            index=models.Index(fields=['practitioner'], name='payments_pr_practit_6af031_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerearnings',
            index=models.Index(fields=['available_balance_cents'], name='payments_pr_availab_35ea78_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerpayout',
            index=models.Index(fields=['practitioner'], name='payments_pr_practit_433ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerpayout',
            index=models.Index(fields=['status'], name='payments_pr_status_e4252d_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerpayout',
            index=models.Index(fields=['payout_date'], name='payments_pr_payout__89be5e_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerpayout',
            index=models.Index(fields=['batch_id'], name='payments_pr_batch_i_92f95a_idx'),
        ),
        migrations.AddIndex(
            model_name='earningstransaction',
            index=models.Index(fields=['practitioner', 'status'], name='payments_ea_practit_253564_idx'),
        ),
        migrations.AddIndex(
            model_name='earningstransaction',
            index=models.Index(fields=['booking'], name='payments_ea_booking_59408d_idx'),
        ),
        migrations.AddIndex(
            model_name='earningstransaction',
            index=models.Index(fields=['status', 'available_after'], name='payments_ea_status_8ab71b_idx'),
        ),
        migrations.AddIndex(
            model_name='earningstransaction',
            index=models.Index(fields=['payout'], name='payments_ea_payout__92144d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetypecommission',
            index=models.Index(fields=['service_type'], name='service_typ_service_fd232e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetypecommission',
            index=models.Index(fields=['is_active'], name='service_typ_is_acti_b17a15_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionersubscription',
            index=models.Index(fields=['practitioner'], name='practitione_practit_1c098c_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionersubscription',
            index=models.Index(fields=['status'], name='practitione_status_b418b2_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionersubscription',
            index=models.Index(fields=['start_date'], name='practitione_start_d_ccbbde_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionersubscription',
            index=models.Index(fields=['end_date'], name='practitione_end_dat_1a96e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tiercommissionadjustment',
            index=models.Index(fields=['tier'], name='tier_commis_tier_id_316dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='tiercommissionadjustment',
            index=models.Index(fields=['service_type_commission'], name='tier_commis_service_11bac0_idx'),
        ),
        migrations.AddIndex(
            model_name='tiercommissionadjustment',
            index=models.Index(fields=['is_active'], name='tier_commis_is_acti_44ad41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiercommissionadjustment',
            unique_together={('tier', 'service_type_commission')},
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['user', 'created_at'], name='payments_us_user_id_502330_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['practitioner', 'created_at'], name='payments_us_practit_ae08e8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='payments_us_transac_2c5a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['order'], name='payments_us_order_i_7b7e95_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['booking'], name='payments_us_booking_5eb801_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredittransaction',
            index=models.Index(fields=['expires_at'], name='payments_us_expires_094a93_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercredittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='payments_usercredittransaction_amount_nonzero'),
        ),
        migrations.AddIndex(
            model_name='usercreditbalance',
            index=models.Index(fields=['user'], name='payments_us_user_id_cc2aac_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreditbalance',
            index=models.Index(fields=['balance_cents'], name='payments_us_balance_af4d5c_idx'),
        ),
    ]
