# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0004_initial"),
        ("payments", "0003_initial"),
        ("practitioners", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalservicefee",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_fees",
                to="services.servicetype",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders_as_practitioner",
                to="practitioners.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="packagecompletionrecord",
            name="package_booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion_record",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practitionercredittransaction",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="credit_transactions",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="practitionercredittransaction",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="practitioners.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="practitionercredittransaction",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practitionerpayout",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="practitioners.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="practitionerpayout",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="practitionercredittransaction",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.practitionerpayout",
            ),
        ),
        migrations.AddField(
            model_name="practitionersubscription",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="practitioners.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="servicetypecommission",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_rates",
                to="services.servicetype",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiontier",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_a7d112_idx"
            ),
        ),
        migrations.AddField(
            model_name="practitionersubscription",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to="payments.subscriptiontier",
            ),
        ),
        migrations.AddField(
            model_name="tiercommissionadjustment",
            name="service_type_commission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier_adjustments",
                to="payments.servicetypecommission",
            ),
        ),
        migrations.AddField(
            model_name="tiercommissionadjustment",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_adjustments",
                to="payments.subscriptiontier",
            ),
        ),
        migrations.AddField(
            model_name="usercreditbalance",
            name="last_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.credittransaction",
            ),
        ),
        migrations.AddField(
            model_name="usercreditbalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_balance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="externalservicefee",
            index=models.Index(
                fields=["service_type"], name="external_se_service_e6217f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalservicefee",
            index=models.Index(
                fields=["is_active"], name="external_se_is_acti_02b508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="orders_user_id_51663a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["practitioner", "created_at"], name="orders_practit_3f366e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "created_at"], name="credit_tran_user_id_309a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["practitioner", "created_at"],
                name="credit_tran_practit_1ff60a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="credit_tran_transac_5168f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(fields=["order"], name="credit_tran_order_i_38e18e_idx"),
        ),
        migrations.AddIndex(
            model_name="packagecompletionrecord",
            index=models.Index(
                fields=["package_booking"], name="package_com_package_2c7b95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagecompletionrecord",
            index=models.Index(fields=["status"], name="package_com_status_2e2c7e_idx"),
        ),
        migrations.AddIndex(
            model_name="packagecompletionrecord",
            index=models.Index(
                fields=["payout_processed"], name="package_com_payout__37af23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionerpayout",
            index=models.Index(
                fields=["practitioner"], name="practitione_practit_9149c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionerpayout",
            index=models.Index(fields=["status"], name="practitione_status_b52689_idx"),
        ),
        migrations.AddIndex(
            model_name="practitionerpayout",
            index=models.Index(
                fields=["payout_date"], name="practitione_payout__95a8ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionerpayout",
            index=models.Index(
                fields=["batch_id"], name="practitione_batch_i_147d30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionercredittransaction",
            index=models.Index(
                fields=["practitioner", "created_at"],
                name="practitione_practit_00fc8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practitionercredittransaction",
            index=models.Index(
                fields=["payout_status"], name="practitione_payout__f50fcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionercredittransaction",
            index=models.Index(
                fields=["payout"], name="practitione_payout__c75781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionercredittransaction",
            index=models.Index(
                fields=["transaction_type"], name="practitione_transac_78537f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionercredittransaction",
            index=models.Index(
                fields=["batch_id"], name="practitione_batch_i_4b725e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypecommission",
            index=models.Index(
                fields=["service_type"], name="service_typ_service_fd232e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypecommission",
            index=models.Index(
                fields=["is_active"], name="service_typ_is_acti_b17a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionersubscription",
            index=models.Index(
                fields=["practitioner"], name="practitione_practit_1c098c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionersubscription",
            index=models.Index(fields=["status"], name="practitione_status_b418b2_idx"),
        ),
        migrations.AddIndex(
            model_name="practitionersubscription",
            index=models.Index(
                fields=["start_date"], name="practitione_start_d_ccbbde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionersubscription",
            index=models.Index(
                fields=["end_date"], name="practitione_end_dat_1a96e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tiercommissionadjustment",
            index=models.Index(fields=["tier"], name="tier_commis_tier_id_316dbc_idx"),
        ),
        migrations.AddIndex(
            model_name="tiercommissionadjustment",
            index=models.Index(
                fields=["service_type_commission"],
                name="tier_commis_service_11bac0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tiercommissionadjustment",
            index=models.Index(
                fields=["is_active"], name="tier_commis_is_acti_44ad41_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tiercommissionadjustment",
            unique_together={("tier", "service_type_commission")},
        ),
        migrations.AddIndex(
            model_name="usercreditbalance",
            index=models.Index(fields=["user"], name="user_credit_user_id_82b75f_idx"),
        ),
    ]
