# Generated by Django 5.1.8 on 2025-05-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credittransaction',
            new_name='payments_cr_user_id_b05307_idx',
            old_name='credit_tran_user_id_309a15_idx',
        ),
        migrations.RenameIndex(
            model_name='credittransaction',
            new_name='payments_cr_practit_782923_idx',
            old_name='credit_tran_practit_1ff60a_idx',
        ),
        migrations.RenameIndex(
            model_name='credittransaction',
            new_name='payments_cr_transac_6cb56f_idx',
            old_name='credit_tran_transac_5168f4_idx',
        ),
        migrations.RenameIndex(
            model_name='credittransaction',
            new_name='payments_cr_order_i_76a20d_idx',
            old_name='credit_tran_order_i_38e18e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='payments_or_user_id_f610cb_idx',
            old_name='orders_user_id_51663a_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='payments_or_practit_1655d9_idx',
            old_name='orders_practit_3f366e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='payments_or_status_daab12_idx',
            old_name='orders_status_762191_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionercredittransaction',
            new_name='payments_pr_practit_4a0c33_idx',
            old_name='practitione_practit_00fc8c_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionercredittransaction',
            new_name='payments_pr_payout__d058ac_idx',
            old_name='practitione_payout__f50fcc_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionercredittransaction',
            new_name='payments_pr_payout__12459c_idx',
            old_name='practitione_payout__c75781_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionercredittransaction',
            new_name='payments_pr_transac_269619_idx',
            old_name='practitione_transac_78537f_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionercredittransaction',
            new_name='payments_pr_batch_i_3ec446_idx',
            old_name='practitione_batch_i_4b725e_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionerpayout',
            new_name='payments_pr_practit_433ed0_idx',
            old_name='practitione_practit_9149c8_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionerpayout',
            new_name='payments_pr_status_e4252d_idx',
            old_name='practitione_status_b52689_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionerpayout',
            new_name='payments_pr_payout__89be5e_idx',
            old_name='practitione_payout__95a8ff_idx',
        ),
        migrations.RenameIndex(
            model_name='practitionerpayout',
            new_name='payments_pr_batch_i_92f95a_idx',
            old_name='practitione_batch_i_147d30_idx',
        ),
        migrations.AlterModelTable(
            name='credittransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='practitionercredittransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='practitionerpayout',
            table=None,
        ),
    ]
