# Generated by Django 5.1.3 on 2025-06-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_stripe_ids_to_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='code',
            field=models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('premium', 'Premium')], help_text='Fixed tier identifier used in code', max_length=20, null=True, unique=True),
        ),
    ]
