# Generated by Django 5.1.3 on 2025-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_make_tier_code_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningstransaction',
            name='status',
            field=models.CharField(choices=[('projected', 'Projected'), ('pending', 'Pending'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='projected', max_length=20),
        ),
    ]
