# Generated by Django 5.1.3 on 2025-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_add_projected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_metadata',
            field=models.JSONField(blank=True, help_text='Package/bundle specific data', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('direct', 'Direct Service Purchase'), ('credit', 'Credit Purchase'), ('package', 'Package Purchase'), ('bundle', 'Bundle Purchase'), ('subscription', 'Subscription')], default='direct', max_length=20),
        ),
    ]
