# Generated by Django 5.1.3 on 2026-03-18 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_add_soft_delete_to_earnings_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='earningstransaction',
            new_name='payments_ea_public__06ea53_idx',
            old_name='payments_ea_public__idx',
        ),
        migrations.AlterField(
            model_name='earningstransaction',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public UUID for API exposure', unique=True),
        ),
    ]
