# Generated by Django 5.1.7 on 2025-03-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="apply_video_processing",
            field=models.BooleanField(
                default=True, help_text="Apply video processing to the video"
            ),
        ),
    ]
