# Generated by Django 5.1.3 on 2025-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether to feature this modality on homepage and marketing'),
        ),
        migrations.AddField(
            model_name='modality',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='modality',
            index=models.Index(fields=['slug'], name='common_moda_slug_372172_idx'),
        ),
        migrations.AddIndex(
            model_name='modality',
            index=models.Index(fields=['is_featured'], name='common_moda_is_feat_9138a1_idx'),
        ),
    ]
