# Generated by Django 5.1.3 on 2025-11-17 20:29

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing Modality records."""
    Modality = apps.get_model('common', 'Modality')

    for modality in Modality.objects.all():
        if not modality.slug:
            modality.slug = slugify(modality.name)
            modality.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - set slugs to None."""
    Modality = apps.get_model('common', 'Modality')
    Modality.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_modality_is_featured_modality_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
