# Generated by Django 5.1.3 on 2026-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_populate_modality_content'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modality',
            new_name='common_moda_categor_80d7eb_idx',
            old_name='common_moda_categor_idx',
        ),
        migrations.AlterField(
            model_name='modality',
            name='category',
            field=models.CharField(blank=True, help_text='Modality category for grouping (legacy)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modalitycategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
