# Generated by Django 5.1.7 on 2025-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioner",
            name="video_presentation_url",
        ),
        migrations.RemoveField(
            model_name="practitioner",
            name="youtube_video_id",
        ),
        migrations.AddField(
            model_name="practitioner",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the practitioner's profile image stored in Cloudflare R2",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="profile_video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the practitioner's profile video stored in Cloudflare R2",
                null=True,
            ),
        ),
    ]
