# Generated by Django 5.1.7 on 2025-04-16 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0004_alter_schedule_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('certification', 'Professional Certification'), ('license', 'Professional License'), ('insurance', 'Insurance Document'), ('background_check', 'Background Check'), ('other', 'Other Document')], max_length=50)),
                ('document_url', models.URLField(help_text='URL to the document stored in Cloudflare R2')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='practitioners.practitioner')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'verification_documents',
                'indexes': [models.Index(fields=['practitioner'], name='vd_practitioner_idx'), models.Index(fields=['document_type'], name='vd_type_idx'), models.Index(fields=['status'], name='vd_status_idx'), models.Index(fields=['expires_at'], name='vd_expiry_idx')],
            },
        ),
    ]
