# Generated by Django 5.1.3 on 2025-06-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_add_client_note'),
        ('practitioners', '0005_make_practitioner_slug_required'),
    ]

    operations = [
    ]
