# Generated by Django 5.1.8 on 2025-05-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0005_certification_expiry_date_certification_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='practitioner',
            new_name='practitione_is_veri_f67cad_idx',
            old_name='practitione_is_veri_491663_idx',
        ),
        migrations.RenameIndex(
            model_name='practitioner',
            new_name='practitione_feature_673f5d_idx',
            old_name='practitione_feature_0a72f7_idx',
        ),
        migrations.RenameIndex(
            model_name='practitioner',
            new_name='practitione_practit_43bb21_idx',
            old_name='practitione_practit_64df68_idx',
        ),
        migrations.RenameIndex(
            model_name='practitioner',
            new_name='practitione_average_3b6a8a_idx',
            old_name='practitione_average_fba9bb_idx',
        ),
        migrations.AlterModelTable(
            name='practitioner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schedule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schedulepreference',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scheduletimeslot',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceschedule',
            table=None,
        ),
    ]
