# Generated by Django 5.1.3 on 2025-06-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_stripe_ids_to_subscription_tier'),
        ('practitioners', '0007_rename_practitione_practit_d5a0f5_idx_practitione_practit_11856a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='current_subscription',
            field=models.ForeignKey(blank=True, help_text='Current active subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.practitionersubscription'),
        ),
    ]
