# Generated by Django 5.1.3 on 2025-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0008_add_current_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Practitioner's profile image (stored in R2)", null=True, upload_to='practitioners/profiles/%Y/%m/'),
        ),
    ]
