# Generated by Django 5.1.3 on 2025-11-19 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0009_remove_practitioner_profile_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short title/summary of the feature request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the feature request')),
                ('category', models.CharField(choices=[('scheduling', 'Scheduling'), ('payments', 'Payments & Billing'), ('analytics', 'Analytics & Reports'), ('client_management', 'Client Management'), ('messaging', 'Messaging'), ('ui_ux', 'UI/UX'), ('mobile', 'Mobile App'), ('integrations', 'Integrations'), ('other', 'Other')], default='other', help_text='Category of the feature request', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text="Practitioner's perceived priority", max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='submitted', help_text='Current status of the request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin/development team', null=True)),
                ('votes', models.PositiveIntegerField(default=0, help_text='Number of practitioners who voted for this feature')),
                ('practitioner', models.ForeignKey(help_text='Practitioner who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='feature_requests', to='practitioners.practitioner')),
            ],
            options={
                'verbose_name': 'Feature Request',
                'verbose_name_plural': 'Feature Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['practitioner', '-created_at'], name='practitione_practit_a670a3_idx'), models.Index(fields=['status', '-created_at'], name='practitione_status_ae48ee_idx'), models.Index(fields=['category', '-created_at'], name='practitione_categor_f30714_idx')],
            },
        ),
    ]
