# Generated by Django 5.1.3 on 2025-11-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0010_add_feature_request_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='The answer to the question', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='The practitioner this FAQ belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to='practitioners.practitioner'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, help_text='The question text', null=True),
        ),
    ]
