# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityfollow",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_followers",
                to="practitioners.practitioner",
            ),
        ),
    ]
