# Generated by Django 5.1.7 on 2025-03-24 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0002_initial"),
        ("practitioners", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communityfollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_follows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="communitytopic",
            index=models.Index(fields=["slug"], name="community_t_slug_5eef3e_idx"),
        ),
        migrations.AddIndex(
            model_name="communitytopic",
            index=models.Index(
                fields=["is_featured"], name="community_t_is_feat_9db646_idx"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="practitioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="practitioners.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="community.communitytopic"
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="community.postcomment",
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="community.post",
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postpurchasevisibility",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_visibility",
                to="community.post",
            ),
        ),
        migrations.AddField(
            model_name="postpurchasevisibility",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_posts",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="community.post",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="communityfollow",
            index=models.Index(fields=["user"], name="community_f_user_id_3e5937_idx"),
        ),
        migrations.AddIndex(
            model_name="communityfollow",
            index=models.Index(
                fields=["practitioner"], name="community_f_practit_7008e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "practitioner"), name="unique_user_practitioner_follow"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["practitioner"], name="community_p_practit_6ca6e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility"], name="community_p_visibil_dea6bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="community_p_created_40799e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_pinned"], name="community_p_is_pinn_0efb42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_featured"], name="community_p_is_feat_1c92ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["post"], name="community_p_post_id_a2e5b5_idx"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["user"], name="community_p_user_id_70abb0_idx"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["created_at"], name="community_p_created_017ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["parent_comment"], name="community_p_parent__79e61b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postpurchasevisibility",
            index=models.Index(fields=["post"], name="community_p_post_id_e8c691_idx"),
        ),
        migrations.AddIndex(
            model_name="postpurchasevisibility",
            index=models.Index(
                fields=["service"], name="community_p_service_4c9196_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postpurchasevisibility",
            constraint=models.UniqueConstraint(
                fields=("post", "service"), name="unique_post_service_visibility"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(fields=["post"], name="community_p_post_id_eec9bc_idx"),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(fields=["user"], name="community_p_user_id_86f3fa_idx"),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["reaction_type"], name="community_p_reactio_95e7b9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.UniqueConstraint(
                fields=("post", "user", "reaction_type"),
                name="unique_user_reaction_per_post",
            ),
        ),
    ]
