# Generated by Django 5.1.3 on 2025-06-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='public_uuid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='public_uuid',
        ),
    ]
