# Generated by Django 5.1.8 on 2025-05-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='messaging_c_created_ab9bdf_idx',
            old_name='conversatio_created_694913_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='messaging_c_updated_7cd0af_idx',
            old_name='conversatio_updated_8d1310_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_convers_7bc91b_idx',
            old_name='messages_convers_3ebb41_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__259b0b_idx',
            old_name='messages_sender__6ae55a_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_is_dele_12264e_idx',
            old_name='messages_is_dele_54348c_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='messaging_m_user_id_ded10d_idx',
            old_name='message_rec_user_id_a4eea2_idx',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.AlterModelTable(
            name='messagereceipt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='typingindicator',
            table=None,
        ),
    ]
