# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_conversation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereceipt',
            name='email_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='messagereceipt',
            index=models.Index(fields=['is_read', 'email_notified_at', 'delivered_at'], name='messaging_m_is_read_idx'),
        ),
    ]
