# Generated by Django 5.1.3 on 2025-11-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagereceipt_email_notified_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='messaging_m_is_read_0e9977_idx',
            old_name='messaging_m_is_read_idx',
        ),
    ]
