# Generated by Django 5.1.3 on 2026-03-24 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rename_messaging_m_is_read_idx_messaging_m_is_read_0e9977_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_deleted', '-created_at'], name='messaging_m_convers_a6ddfd_idx'),
        ),
    ]
