# Generated by Django 5.1.3 on 2025-06-21 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_make_service_slug_required'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user favorite service',
                'verbose_name_plural': 'user favorite services',
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_userf_user_id_34cdc1_idx'), models.Index(fields=['service'], name='users_userf_service_b34215_idx')],
                'unique_together': {('user', 'service')},
            },
        ),
    ]
