# Generated by Django 5.1.3 on 2025-06-21 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_add_user_favorite_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModalityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority order (0 = highest priority)')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='common.modality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modality_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user modality preference',
                'verbose_name_plural': 'user modality preferences',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['user', 'priority'], name='users_userm_user_id_274afa_idx'), models.Index(fields=['modality'], name='users_userm_modalit_756846_idx')],
                'unique_together': {('user', 'modality')},
            },
        ),
    ]
